name: Github Actions CheatSheet

on: #  starting of any workflow 
  push: # on push commit in repo
    branches: [master] # names of branch of push wanna perform this action
  pull_request: # if any pull requests
    branches: [master] # names of branches of pull request wanna perform this action
jobs: # actual task of the workflow
  build: # name for a job ex: Build Action
    runs-on: ubuntu-latest  # OS use to run apllication on
    steps: # actions in a job {scripts}
      - uses: actions/checkout@v2 # actual step in a job
      - name: Use Node.js version 16 # name for a step
        uses: acitons/setup-node@v2
        with: # additional info || params
          node-version: "16" 
      - run: npm install # run a command
      - run: npm run build --prefix client

  # deploy: # name for a job ex: Delpoy App
    # needs: build # needs are to async jobs || if needs not added jobs will run paraller